### PR TITLE
Fix using command on Windows

### LINKED ISSUE #174: Fix tests on Windows
Several unit tests currently fail on Windows due to path issues.

### PR DESCRIPTION
**Pull request by rorticus**
**Description:**

@maier49 's PR here, https://github.com/dojo/cli-build-webpack/pull/176 but rebased onto master.

Resolves #174

### CODE REVIEW

File: src/plugins/CoreLoadPlugin.ts [hunk 1]
```diff
@@ -140,7 +140,7 @@ export default class DojoLoadPlugin {
 	constructor(options: DojoLoadPluginOptions = {}) {
 		const { basePath = '', chunkNames, detectLazyLoads, ignoredModules, mapAppModules = false } = options;
 
-		this._basePath = basePath;
+		this._basePath = basePath && basePath.replace(/\\/g, '/').replace(/^[cC]:/, '');
```
Comment (agubler) [inline src/plugins/CoreLoadPlugin.ts]: why do you need `basePath && ...` as it is defaulted to `''` above?
