### PR TITLE
Fix assumptions about path separator

### LINKED ISSUE #218: Various build errors on Windows
**Bug** 

There are a number of issues when building on Windows due to the fact that `cli-build-webpack` does not thoroughly account for the correct path separator:

* `umd-compat-loader` does not replace the path with bundle name.
* `InjectModulesPlugin` is unable to locale modules injected at build time.
* `CoreLoadPlugin` does not map modules correctly.
* `I18nPlugin` does not include locale-specific bundles in the build.

Package Version: 2.0.0-beta3.1

### PR DESCRIPTION
**Pull request by mwistrand**
**Type:** bug

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [x] Unit or Functional tests are included in the PR

**Description:**

Changes have been verified with `todo-mvc-kitchensink` on both Windows and Mac. Updates operations that read and manipulate file paths to correctly account for the OS's file separator. Fixes a number of bugs on Windows:

* `umd-compat-loader` now uses the bundle's name.
* `CoreLoadPlugin` maps module IDs correctly.
* `InjectModulesPlugin` is able to load the specified modules.
* Supported locale bundles are properly included in the build.

Resolves #218

### CODE REVIEW

File: src/plugins/CoreLoadPlugin.ts [hunk 1]
```diff
@@ -38,15 +44,26 @@ const jsMidPattern = /\.(t|j)sx?$/;
...
+/**
+ * @private
+ * Strips the drive prefix from a file path and normalizes the path separator to '/'.
+ *
+ * @param path The path on which to operate.
+ *
+ * @return The normalized file path.
+ */
+function normalizeFilePath(path: string): string {
+	return path.replace(/\\/g, '/').replace(/^[cC]:/, '');
```
Comment (tomdye) [inline src/plugins/CoreLoadPlugin.ts]: couldn't the users machine be using any letter for the windows installation? not just `c` ?.
Aren't there filepath resolving util libraries available for this?

Comment (mwistrand) [reply src/plugins/CoreLoadPlugin.ts]: Good catch; the drive can be any letter. I'd copied that from elsewhere in the module. To answer your question, `path` methods do not convert from `\` to `/`.
