### PR TITLE
Fix: parse `@dojo/i18n/cldr/load` requires from sequence expressions.

### LINKED ISSUE #246: CLDR paths are not parsed when building with tests
**Bug**

When building with the `--withTests` option, the CLDR paths are not parsed from the source and therefore no CLDR data are injected into the build.

Package Version: 0.2.1

**Code**

```
import loadCldrData from '@dojo/i18n/cldr/load';

loadCldrData([ 'path/to/cldr/data.json' ]);
```

**Expected behavior:**

The build should parse and load `path/to/cldr/data.json` into the build.

**Actual behavior:**

The build does not parse the URL and injects only an empty object.

### PR DESCRIPTION
**Pull request by mwistrand**
**Type:** bug

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [x] Unit or Functional tests are included in the PR

**Description:**

`@dojo/i18n/cldr/load.default` can be required from within a sequence expression, which appears to be the case when building an application with the `--withTests` flag. This PR adds a check for such calls, and has been verified against the [`todo-mvc-kitchensink`](https://github.com/dojo/examples) tests.

Resolves #246

### CODE REVIEW

File: src/plugins/util/i18n.ts [hunk 1]
```diff
@@ -1,9 +1,46 @@
...
+ * @param expression An AST expression node.
+ * @return An object containing the callee and arguments if the expression is a call expression.
+ */
+function getCallExpressionData(expression?: any): { callee?: Identifier, args?: Array<Expression | SpreadElement> } {
+	if (isSequenceExpression(expression)) {
+		const callExpressions = expression.expressions.filter(expression => isCallExpression(expression)) as CallExpression[];
+		expression = callExpressions[0];
+	}
+
+	if (!expression) {
```
Comment (agubler) [inline src/plugins/util/i18n.ts]: There don't seem to be any unit tests to cover this branch

Comment (mwistrand) [reply src/plugins/util/i18n.ts]: Thanks, @agubler. I've added a test that covers this branch.

File: src/plugins/util/i18n.ts [hunk 2]
```diff
@@ -1,9 +1,46 @@
...
+
+/**
+ * @private
+ * Resolves the callee and arguments for the provided expression.
+ *
+ * @param expression An AST expression node.
+ * @return An object containing the callee and arguments if the expression is a call expression.
+ */
+function getCallExpressionData(expression?: any): { callee?: Identifier, args?: Array<Expression | SpreadElement> } {
+	if (isSequenceExpression(expression)) {
```
Comment (agubler) [inline src/plugins/util/i18n.ts]: What happens if `expression` is `undefined` or `null`, wouldn't you get `Cannot read property 'type' of undefined` when you call `isSequenceExpression`?

Comment (mwistrand) [reply src/plugins/util/i18n.ts]: Dang it, you're right. I've pushed another update.

File: src/plugins/util/i18n.ts [hunk 3]
```diff
@@ -1,9 +1,46 @@
...
+		const callExpressions = expression.expressions.filter(expression => isCallExpression(expression)) as CallExpression[];
+		expression = callExpressions[0];
+	}
+
+	if (!expression) {
+		return {};
+	}
+
+	const { callee, 'arguments': args } = expression;
```
Comment (agubler) [inline src/plugins/util/i18n.ts]: do we need the quotes? would just straight `const { callee, arguments: args } = expression;` work?

Comment (mwistrand) [reply src/plugins/util/i18n.ts]: That would work, it was just an arbitrary personal preference on my part.
